### ISSUE TITLE
Mute confirmation

### ISSUE THREAD

**Issue by smcllns** [andreyLevushkin/Techmeetup-Site#4]
When I mute a conversation - I want confirmation that I did indeed mute it, rather than just landing on the blog page. Is it required that the user lands on the site?

Can there just be a pop up of some sort that says

"Thanks, you will not receive any further email notifications on this topic. Enjoy your day!"

**Comment by andreyLevushkin** [comment]
Can't have popups as the user can be viewing the email on a phone or an email client with no JavaScript support. Even if the user is using a web client to view the email then the JavaScript is likely to be blocked anyway. 
I think i will change it so that you are redirected to a page that says that this conversation has been muted.
